// netlify/functions/github-agent.js
export default async (request) => {
  if (request.method !== 'POST') {
    return new Response('Method not allowed', { status: 405 });
  }
  
  const payload = await request.json();
  console.log('Received payload:', JSON.stringify(payload));
  
  // Nahraď svými reálnými hodnotami
  const REPO_OWNER = 'tvuj-github-nick';  // ← TVOJE NICK
  const REPO_NAME = 'zahradkar-app';       // ← tvé repo
  const GITHUB_TOKEN = process.env.GITHUB_TOKEN; // ← nastavíš v Netlify Environment variables
  
  const dispatchUrl = `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/workflows/code-agent.yml/dispatches`;
  
  const response = await fetch(dispatchUrl, {
    method: 'POST',
    headers: {
      'Authorization': `token ${GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      ref: 'main',
      inputs: {
        feature: payload.feature || 'unknown',
        description: payload.description || 'Generated by Perplexity Agent',
        files: (payload.files || []).join(',')
      }
    })
  });
  
  const result = await response.json();
  console.log('GitHub dispatch result:', JSON.stringify(result));
  
  return new Response(JSON.stringify({ success: true, result }), { 
    status: 200,
    headers: { 'Content-Type': 'application/json' }
  });
};

